debrajhyper/Topic_Learning_Resources

README.md
I added some resources from my most popular blogpost
=> Added HTML, CSS, JavaScript resources

README.md
This is a great advanced play list which I found very useful and would like to share with everyone.
I also fixed a couple of typos. Let me know if you have any questions?
Have a great day! Elena 😃
=> Added python advanced playlist & fixed typos

README.md
Adding YouTube Playlist of C++ Course taught by Apna College 
**Note** 
-  Contributing Under Hactoberfest2021
=> Adding Resource for CPP in Programming Topic 

README.md
I have added a golang playlist under the programming section and a great beginner playlist for MongoDB in the backend section.
Could you please review my PR and merge in under __hacktoberfest-accepted__ tag?
=> Add tutorial links

README.md
www.joshwcomeau.com/tutorials/css/
=> Best website to learn css visually

README.md
Added free resource for python learning
=> Added link for python file

README.md
Added the best flutter resources.
=> Added the best flutter resources.

README.md
Javascript.info is one of the best site to learn javascript
https://javascript.info
=> Add 1 resource to learn Javascript

README.md
Added Statistics Fundamentals by StatQuest in the Data Science section.
=> Added "Statistics Fundamentals" in DS section

CONTRIBUTING.md
Have added two new great resources for Python and Microsoft Excel
=> Resources by TK

README.md
Added New Resources-
CS50 and coding blocks jr 2020 Playlist For coding including-
=> Added New Resources Hacktoberfest22 Participant

README.md
I have moved the section with programming competitions out of the documentation section and into it's own section as this does not belong to documentation.
=> Moved websites for programming competitions

README.md
=> Added android development resources

README.md
Scrimba Javascript tutorial added.
Line added at 91 in README.md file.
Link to resource: https://scrimba.com/learn/learnjavascript
=> scrimba-js-course

README.md
I have added many resources for competitive programming and also made changes to table of contents accordingly. Text based or books or website resources were are added in the documentation section and video tutorials in video/playlist. I have added all the resources that I know of and will update if i find some more. I have also removed Websites for programming competitions and instead added all of them in  Websites For Programming Contests and Practice under Competitve Programming in a nice fashion. Do let me know for any changes to be made. And thanks for starting such a nice project!
=> Added Resorces For Competitive Programming

README.md
Added 7 resources
-HTML/CSS/JavaScript
-Javascript full course
-Git and GitHub overview and practical uses
-NodeJS resources
-Data Structures YT playlist
-C++ complete DSA course
-C++ STL video
=> Added 7 learning resources to README.md

README.md
Add Some useful resourecs of DSA ,HTML and CSS
=> Add DSA, HTML and CSS resources

CONTRIBUTING.md
1 change in Games to Learn Tech
=> Add Css Diner

CONTRIBUTING.md, README.md
hello sir here i add some learning resources related to programming
=> add new learn learning resources

CONTRIBUTING.md
=> Add Groovy Documentation

CONTRIBUTING.md
=> Add Java Tutorial

CONTRIBUTING.md
=> Sql documentation add

README.md
Total number of changes/resources added  - 3 (Docs - 2, Programming resource - 1)
Docs added
Flask : Docs - https://flask.palletsprojects.com
This official Flask documentation shows code examples and builds a web app. Level - intermediate python development.
Jinja : Docs - https://jinja.palletsprojects.com
This is the official Jinja documentation. Jinja is a templating engine which allows writing python line syntax inside an HTML file
Programming Link added:
Python Flask tutorial - https://youtu.be/Qr4QMBUPxWo
This is a beginner-level Flask tutorial which teaches basics and builds a marketplace application.
=> Python Flask tutorial link and Documentation for Flask and Jinja added

CONTRIBUTING.md
Added Angular Course Please Check
=> Angular Course For Beginners 

README.md
- Added GoLang official doc link
- Added GoLang hands-on learning resource doc link
=> Add 2 GoLang Doc links to README.md

README.md
Perl officially stands for Practical Extraction and Report Language,
=> Added Perl Documentation

README.md
=> Added CSS  video

README.md
=> Add sql resources

CONTRIBUTING.md
Added Data Science and ML Video Tutorials.
=> Added Data Science and Machine Learning Video Tutorials

README.md
=> add golang docs

README.md
Added Official C# documentation link.
=> Add C# doc to README.md

README.md
A guide to learning blockchain development 🚀.
Could you please review this @Debajyotighosh654 @debrajhyper
=> Blockchain Development Content Added

README.md
Learn CSS flexbox and grid while playing the game
=> CSS resources

README.md
Ruby on Rails Video Tutorials Added in Backend Development
=> Backend Development Resources added

web3_learning
=> web3 and blockchain resources

README.md
Added Laracasts (https://laracasts.com) to the backend section and Caleb Curry's C++ course (https://www.youtube.com/watch?v=_bYFu9mBnr4) to the programming section. Total changes: 2
=> Added 2 new resources

README.md
Firstly I have added a website 'hackerearth' under 'programming competitions' heading. Secondly I have added a site from W3Schools in 'html' section of 'developement doc' heading. Third and last thing is that I have added ' Java Complete Course - Placement series by Apna College' in the heading 'DSA'
=> Added one programming competition resource and two learning resources.

README.md
added 3 links for Native android development resources which will help beginners to kickstart  their android development journey
=> added 3 android development resources for beginners

README.md
=> add reactjs resource

README.md
=> Added Node, express and full stack course

README.md
Issue #149 
Changes made:
Added 1 programming cometition website Code jam.
Added 2 JavaScript and 1 TypeScript free resource.
Added 1 java resource
Added 1 resource
Resource links:
The odin project -> https://www.theodinproject.com
30 Day Vanilla JS Coding Challenge - https://javascript30.com
JavaTpoint - https://www.javatpoint.com/java-tutorial
Codeinwp -> https://www.codeinwp.com/blog/webpack-tutorial-for-beginners
Resource description:
The odin project -> The Odin Project provides a free open source coding curriculum on web development that can be taken entirely online.
30 Day Vanilla JS Coding Challenge -> It's a 30-day vanilla JS coding challenge. During these 30 days you'll build 30 different apps using fun and easy video tutorials.
JavaTpoint -> It is a Java programming platform. …
=> added resources

README.md
Added Kotlin Programming language offical docs  in official docs section
=> Added Kotlin Programming language offical docs

README.md
#70 
This is my PR w.r.t the previous PR as there were merge conflicts.
Changes Made:
1. Added a new React JS resource playlist
2.  Added a free version control with Git Course
=> Added a New React JS and Git learning Resource 

README.md
The modern JavaScript course for everyone. The instructor is Jonas Schmedtmann. The course has 69 hours of on demand video. The link for the course is - https://www.udemy.com/course/the-complete-javascript-course
=> Added one Video Resource for Frontend Web Development

README.md
added a blender tutorial to misc section
=> add blender tutorial

README.md
I have added the Resource. Kindly Check
=> Added the Frontend Resource

README.md
The Odin Project is an open-source community dedicated to providing the best information sources to take you from zero to a full-stack developer. It is a great place to learn fullstack web devlopment
=> Added The Odin project in HTML/CSS and Javascript section.

README.md
Closes #191 
Added MDN Docs JavaScript as a learning resource for JavaScript
=> Add JS MDN Web docs

CONTRIBUTING.md
Fixes issue #183 
Before:
Fixed:
=> Fix broken table in CONTRIBUTING.md

README.md
=> Convert to hyperlink

README.md
=> Open source resources

README.md
=> Add DevRel resources

README.md
#217 
I have shared my resources that I follow to learn flutter, I hope that you would like these changes
=> Added Flutter Resources

README.md
Added a YouTube resource for learning basics and OOPS in Python.
=> Add Python (Beginner + OOPS) Video Resource

README.md
Fix : #225 
Added high quality android resource. Android Basic to advance free video course by google Android team.
=> Android Resource added

README.md
#229 Add AWS Course Issue Closed .
=> Added aws course

README.md
Fixes #232 
Added ```Kotlin``` resources which are from :
1. Official Android team
2. W3School
=> Fix #232 Added Kotlin resources

README.md
Added a basic introductory tutorial series for the Sketch app. 
https://learnux.io/course/sketch
=> Added Sketch under UI Development

README.md
| TOPIC            | SOURCE NAME      | LINK                                       |
| ---------------- | ---------------- |------------------------------------------- |
|System Design     | Gaurav Sen       | [click here](https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX) |
|System Design     | sudoCODE         | [click here](https://www.youtube.com/playlist?list=PLTCrU9sGyburBw9wNOHebv9SjlE4Elv5a) |
**Added Two System Design Resources**
=> System_design_Resources_Added

README.md
Added the official documentation website for the OCaml functional programming language.
=> Added official documentation for OCaml
